// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: meshtastic_nodes.sql

package db

import (
	"context"
	"database/sql"
)

const meshtasticNodeUpdate = `-- name: MeshtasticNodeUpdate :exec
INSERT INTO meshtastic_nodes (node_num, meshtastic_id, long_name, short_name, mac, hw_model, public_key) VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT (node_num) DO UPDATE SET
    meshtastic_id = excluded.meshtastic_id,
    long_name = excluded.long_name,
    short_name = excluded.short_name,
    mac = excluded.mac,
    hw_model = excluded.hw_model,
    public_key = excluded.public_key
`

type MeshtasticNodeUpdateParams struct {
	NodeNum      int64
	MeshtasticID string
	LongName     sql.NullString
	ShortName    sql.NullString
	Mac          sql.NullString
	HwModel      sql.NullString
	PublicKey    []byte
}

func (q *Queries) MeshtasticNodeUpdate(ctx context.Context, arg MeshtasticNodeUpdateParams) error {
	_, err := q.db.ExecContext(ctx, meshtasticNodeUpdate,
		arg.NodeNum,
		arg.MeshtasticID,
		arg.LongName,
		arg.ShortName,
		arg.Mac,
		arg.HwModel,
		arg.PublicKey,
	)
	return err
}
