// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type Channel struct {
	ID              int64
	MeshtasticIndex int64
	MeshtasticPsk   string
	Name            sql.NullString
	MatrixRoom      sql.NullString
}

type MatrixFilter struct {
	UserID   string
	FilterID string
}

type MatrixNextBatch struct {
	UserID string
	Token  string
}

type MeshtasticNode struct {
	ID           int64
	NodeNum      int64
	MeshtasticID string
	LongName     sql.NullString
	ShortName    sql.NullString
	HwModel      sql.NullString
	PublicKey    []byte
	MatrixID     sql.NullString
}
